kind: Service
apiVersion: v1
metadata:
  name: hello-jakartaee
  labels:
    app: hello-jakartaee
spec:
  type: NodePort
  selector:
    app: hello-jakartaee
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-jakartaee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-jakartaee
  template:
    metadata:
      labels:
        app: hello-jakartaee
        version: v1
    spec:
      containers:
        - name: hello-jakartaee
          image: localhost:5000/hello-jakartaee
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 45
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 45
      restartPolicy: Always